algo = input('Digite algo:')
print('O tipo primitivo desse valor é {}'.format(type(algo)))
print('Só tem espaços? {}'.format(algo.isspace()))
print('É um número? {}'.format(algo.isnumeric()))
print('É alfabetico? {}'.format(algo.isalpha()))
print('É alfanumérico? {}'.format(algo.isalnum()))
print('Está em maiúscula? {}'.format(algo.isupper()))
print('Está em minúscula? {}'.format(algo.islower()))
print('Está capitalizada?? {}'.format(algo.istitle()))